buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        mavenCentral()
        mavenLocal()
    }
    dependencies {
        classpath "com.gradle.publish:plugin-publish-plugin:0.9.1"
        classpath 'ch.poole.misc:gradle-eclipse-aar-plugin:0.1.0'
    }
}

plugins {
    id 'maven-publish'
    id 'com.github.kt3k.coveralls' version '2.3.1'
}

apply plugin: 'groovy'
apply plugin: 'maven-publish'
apply plugin: 'signing'

group = GROUP
version = VERSION_NAME
archivesBaseName = POM_ARTIFACT_ID

ext {
    user = System.getenv('SONATYPE_USER')
    password = System.getenv('SONATYPE_PASSWORD')
}

// To release:
// ./gradlew clean assemble uploadArchives -Prelease
def isReleaseBuild
if (hasProperty("release")) {
    isReleaseBuild = true
}

def sonatypeRepositoryUrl

if (isReleaseBuild) {
    if ("$version".endsWith('-SNAPSHOT')) {
        println "SNAPSHOT BUILD $version"
        sonatypeRepositoryUrl = "https://oss.sonatype.org/content/repositories/snapshots/"
    } else {
        println "RELEASE BUILD $version"
        sonatypeRepositoryUrl = "https://oss.sonatype.org/service/local/staging/deploy/maven2/"
    }
} else {
    println "DEBUG BUILD $version"
    sonatypeRepositoryUrl = "https://oss.sonatype.org/content/repositories/snapshots/"
}

apply from: '../../gradle-tasks/eclipse-3'

// Note: These properties must be defined in ~/.gradle/gradle.properties
// and signing.keyId, signing.password, signing.secretKeyRingFile, too.
def username = hasProperty("nexusUsername") ? project.getProperty("nexusUsername") : ""
def password = hasProperty("nexusPassword") ? project.getProperty("nexusPassword") : ""

dependencies {
    implementation gradleApi()
    implementation localGroovy()
    implementation 'org.apache.maven:maven-artifact:3.3.9'
    testImplementation 'junit:junit:4.13'
    testImplementation 'com.android.tools.build:gradle:1.0.0'
    testImplementation ('org.spockframework:spock-core:2.3-groovy-3.0') {
        exclude group: 'org.codehaus.groovy', module: 'groovy-all'
    }
}

repositories {
    mavenCentral()
}

signing {
    required { isReleaseBuild && gradle.taskGraph.hasTask("uploadArchives") }
    sign configurations.archives
}

task sourcesJar(type: Jar, dependsOn: classes) {
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    archiveClassifier = 'javadoc'
    from javadoc.destinationDir
}

artifacts {
    archives sourcesJar
    archives javadocJar
}

publishing {
    publications {
        plugin(MavenPublication) {
            groupId 'ch.poole.misc'
            artifactId POM_NAME
            version VERSION_NAME

            from components.java
            artifact sourcesJar
            artifact javadocJar
          
            pom {
                name = artifactId
                description = 'Gradle plugin to use Android AAR libraries on Eclipse'
                url = 'https://github.com/simonpoole/gradle-eclipse-aar-plugin'
                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }
                developers {
                    developer {
                        id = 'ksoichiro'
                        name = 'Soichiro Kashima'
                    }
                    developer {
                            name = 'Simon Poole'
                    }
                }
            }
            
            repositories {
                maven {
                    name = 'sonatype'
                    credentials {
                        username = user
                        password = password
                    }
                    def releasesRepoUrl = "https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/"
                    def snapshotsRepoUrl = "https://s01.oss.sonatype.org/content/repositories/snapshots/"
                    url = version.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
                }
            }
        }
    }
}

signing {
    sign publishing.publications.plugin
}
